services:
  - type: web
    name: soybean-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000  # This can be any value; Render replaces it at runtime
