services:
  - type: web
    name: soybean-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 10000  # any dummy value; Render overrides this automatically
    autoDeploy: true
